name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

  # # Allow manual triggering
  # workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          BASE_URL: /${{ github.event.repository.name }}/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .output/public  # The folder the action should deploy
          branch: gh-pages  # The branch the action should deploy to
          clean: true  # Automatically remove deleted files from the deploy branch
